import { LearningBaseOverview, learningBaseDescription } from './LearningBaseOverview';
import { assetCrumbs, usePageBreadcrumbs } from './Breadcrumbs';
import type { WorkspaceSummary } from './WorkspaceTypes';
import { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ClipboardList, Database, FileText, Network, Settings2, Sparkles } from 'lucide-react';
import { formatDate, useResource } from './api';
import { EmptyState, Loading, Notice, PageHeader, StatusBadge } from './components';
import { BaseEditor } from './KnowledgePages';
import { DocumentDirectory } from './DocumentDirectory';
import { sourceKindNames } from './KnowledgeGovernance';
import { businessHref } from './BusinessContext';
import type { KnowledgeBase, KnowledgeDocument, User } from './types';
import type { GraphData } from './GraphTypes';
import './knowledge-workspace.css';
const tabs=[['overview','概览'],['documents','知识文档'],['objects','业务对象与图谱'],['applications','业务应用'],['quality','质量待办'],['settings','管理']] as const;
export function BaseWorkspace({user}:{user:User}) {
 const {id=''}=useParams(); const [params,setParams]=useSearchParams();const allowedTabs=tabs.filter(([key])=>user.role!=='viewer'||!['quality','settings'].includes(key));const tab=allowedTabs.some(([key])=>key===params.get('tab'))?params.get('tab')!:'overview';const [editing,setEditing]=useState(false);
 const bases=useResource<{bases:KnowledgeBase[]}>('/bases');const base=bases.data?.bases.find(row=>row.id===id);
 const trash=tab==='documents'&&params.get('trash')==='1'&&user.role!=='viewer';
 usePageBreadcrumbs(base?[...assetCrumbs,{label:base.name,to:'/assets/knowledge-bases/'+encodeURIComponent(id)+'?tab=overview'},{label:allowedTabs.find(([key])=>key===tab)?.[1]||'概览',...(trash?{to:'/assets/knowledge-bases/'+encodeURIComponent(id)+'?tab=documents'}:{})},...(trash?[{label:'回收站'}]:[])]:null);
 const docs=useResource<{documents:KnowledgeDocument[];pagination?:{total:number;hasMore:boolean}}>('/documents?'+new URLSearchParams({baseId:id,limit:'500'}));
 const graph=useResource<GraphData>('/graph?'+new URLSearchParams({baseId:id,status:'confirmed'}));
 const quality=useResource<WorkspaceSummary>('/workspace/summary?'+new URLSearchParams({baseId:id}));
 const documents=docs.data?.documents||[];const now=Date.now();const due=documents.filter(doc=>doc.reviewDueAt&&Date.parse(doc.reviewDueAt)<=now&&doc.status==='published');const synthetic=documents.filter(doc=>doc.sourceKind==='synthetic');const issues=quality.data?.todos||[];const mayManage=user.role==='admin'||base?.ownerId===user.id;
 const to=(path:string,extra:Record<string,string|number|undefined>={})=>businessHref(path,{baseId:id,...extra});
 if(bases.loading&&!base)return <Loading/>;if(!base)return <Notice kind="error">{bases.error||'知识库不存在或当前工作空间无权访问。'}</Notice>;
 const isLearning=base.systemKind==='feedback_learning';
 const choose=(key:string)=>{if(!allowedTabs.some(([value])=>value===key))return;const next=new URLSearchParams(params);next.set('tab',key);setParams(next);};
 return <div className="e-page kw-base-space"><PageHeader title={base.name} description={isLearning?learningBaseDescription:base.description||'在同一业务范围中使用、维护和核验知识。'} actions={<><Link className="e-btn" to={to('/application/search')}><BookOpen size={16}/>搜索本库</Link><Link className="e-btn primary" to={to('/application/chat')}><Sparkles size={16}/>本库问答</Link></>}/><div className="kw-space-meta"><span><Database size={14}/>{isLearning?'系统内置知识库':base.department||'企业共享知识'}</span><span>{isLearning?'后台自用':base.visibility==='company'?'企业共享':base.visibility==='department'?'部门共享':'指定成员'}</span><span>{quality.data?.documents.total??base.documentCount??documents.length} 份文档版本</span>{synthetic.length>0&&<span className="e-badge review">含 {synthetic.length} 份合成示例</span>}</div><nav className="kw-space-tabs" aria-label="知识库功能">{allowedTabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>choose(key)}>{label}</button>)}</nav>{(docs.error||graph.error||quality.error)&&<Notice kind="error">{docs.error||graph.error||quality.error}</Notice>}{tab==='overview'&&docs.data?.pagination?.hasMore&&<Notice kind="warning">概览按最近更新的资料展示；全部文档可在本页“知识文档”中搜索与筛选。知识数量按本库完整可见范围汇总。</Notice>}
 {tab==='overview'&&<><div className="kw-summary-grid">{[{label:'当前有效知识',value:quality.data?.documents.published??0,unit:'份',icon:CheckCircle2,key:'documents'},{label:'待审核发布',value:quality.data?.documents.review??0,unit:'份',icon:ClipboardList,key:'quality'},{label:'已到复审日期',value:quality.data?.todoStats.review_due??due.length,unit:'份',icon:FileText,key:'quality'},{label:'已核验业务对象',value:graph.data?.nodes.length??0,unit:'个',icon:Network,key:'objects'}].map(item=><button className="e-card kw-summary" onClick={()=>choose(item.key)} key={item.label}><item.icon size={19}/><span>{item.label}</span><strong>{quality.loading||graph.loading?'—':item.value}<small>{item.unit}</small></strong></button>)}</div><div className="kw-two-columns"><section className="e-card"><div className="e-section-heading"><h2>最近更新的知识</h2><button className="e-text-link" onClick={()=>choose('documents')}>查看全部<ArrowRight size={14}/></button></div><DocumentList documents={[...documents].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5)}/></section>{isLearning?<LearningBaseOverview/>:<section className="e-card kw-scope-card"><h2>业务范围与责任</h2><dl><dt>知识内容</dt><dd>{base.description||'尚未登记，请通过管理补充。'}</dd><dt>责任部门</dt><dd>{base.department||'尚未登记'}</dd><dt>维护责任</dt><dd>{[...new Set(documents.map(doc=>doc.businessOwner).filter(Boolean))].slice(0,5).join('、')||'各文档业务维护责任人，待登记'}</dd><dt>使用原则</dt><dd>问答使用可访问、已发布且有效的资料；原文和历史版本保留供核验。</dd></dl>{synthetic.length>0&&<p className="kw-sample-note">本库含地铁行业合成示例，用于演示业务流程，不代表实际运营记录或正式规章。</p>}</section>}</div></>}
 {tab==='documents'&&<DocumentDirectory user={user} base={base} onChanged={()=>{docs.reload();quality.reload();bases.reload();}}/>}
 {tab==='objects'&&<section className="e-card kw-object-intro"><Network size={35}/><h2>从业务对象连接到资料依据</h2><p>当前返回 {graph.data?.nodes.length??0} 个对象、{graph.data?.edges.length??0} 条已核验关系。线路、车站、设备、工单、问题与规程可以逐级探索。</p>{graph.data?.limits.truncated&&<Notice kind="warning">图谱结果已达到单次返回上限，请按对象类型或名称缩小范围。</Notice>}<div className="e-actions"><Link className="e-btn primary" to={to('/assets/objects')}>打开本库对象目录<ArrowRight size={15}/></Link><Link className="e-btn" to={to('/assets/graph')}>探索完整知识图谱</Link></div></section>}
 {tab==='applications'&&<div className="kw-application-grid">{[{name:'知识搜索',text:'围绕业务任务，查找适用资料、原文和出处。',path:'/application/search',icon:BookOpen},{name:'智能问答',text:'在本库范围内提问，核验引用和证据链。',path:'/application/chat',icon:Sparkles}].map(item=><Link key={item.path} className="e-card kw-app-card" to={to(item.path)}><item.icon size={24}/><h2>{item.name}</h2><p>{item.text}</p><span>已限定本知识库<ArrowRight size={15}/></span></Link>)}</div>}
 {tab==='quality'&&user.role!=='viewer'&&<section className="e-card"><div className="e-section-heading"><h2>本库质量待办</h2><Link className="e-btn" to={to('/governance/overview')}>进入治理工作台<ArrowRight size={15}/></Link></div>{quality.loading?<Loading/>:issues.length?<div className="kw-document-list">{issues.map(issue=><Link key={issue.id} to={issue.route}><ClipboardList size={17}/><div><strong>{issue.title}</strong><p>{issue.description}</p></div><span className="e-badge review">{({review:'待审核',processing:'处理异常',conflict:'冲突核验',review_due:'到期复审',feedback:'用户反馈',evidence:'证据复核'} as Record<string,string>)[issue.kind]||'待核验'}</span></Link>)}</div>:<EmptyState title="本库暂无待处理提醒" description="发布审核、复审安排与解析质量按文档状态持续更新。"/>}</section>}
 {tab==='settings'&&user.role!=='viewer'&&<section className="e-card e-stack"><div className="e-section-heading"><h2>知识库管理</h2>{mayManage&&<button className="e-btn" onClick={()=>setEditing(true)}><Settings2 size={16}/>编辑知识库设置</button>}</div><dl className="e-definition-grid"><div><dt>所属部门</dt><dd>{base.department||'尚未登记'}</dd></div><div><dt>创建时间</dt><dd>{formatDate(base.createdAt)}</dd></div><div><dt>共享范围</dt><dd>{base.visibility==='company'?'企业共享':base.visibility==='department'?'部门共享':'指定成员'}</dd></div><div><dt>使用边界</dt><dd>本库设置统一作用于资料、检索、问答、图谱和原件访问。</dd></div></dl>{!mayManage&&<p className="e-muted">由库负责人或管理员修改知识库设置。</p>}</section>}{editing&&<BaseEditor base={base} user={user} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);bases.reload();}}/>}</div>;
}
function DocumentList({documents}:{documents:KnowledgeDocument[]}) {return documents.length?<div className="kw-document-list">{documents.map(doc=><Link to={'/documents/'+doc.id} key={doc.id}><span className="e-file-icon"><FileText size={18}/></span><div><strong>{doc.title}</strong><p>V{doc.version} · {sourceKindNames[doc.sourceKind||'unspecified']} · {formatDate(doc.updatedAt)}</p></div><StatusBadge status={doc.status}/><ArrowRight size={15}/></Link>)}</div>:<EmptyState title="尚无可见文档" description="接入资料后，原文、版本与处理状态会显示在这里。"/>;}



